swagger: "2.0"
info:
  title: "API de carros"
  description: "API para gerenciamento de carros"
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /carros:
    get:
      tags:
        - "Carros"
      summary: "Retorna todos os carros cadastrados"
      description: ""
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Carro"
        404:
          description: "Não encontrado"

definitions:
  Carro:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      marca:
        type: "string"
      modelo:
        type: "string"
      ano:
        type: "integer"
        format: "int64"
      placa:
        type: "string"
    xml:
      name: "Carro"
