swagger: '2.0'
info:
  title: API de Gerenciamento de Carros
  version: '1.0'
consumes:
  - application/json
produces:
  - application/json
tags:
  - Carro
parameters:
  - name: id
    in: path
    type: integer
    required: true
  - in: body
    name: body
    schema:
      type: object
      properties:
        marca:
          type: string
          description: Marca do carro
        modelo:
          type: string
          description: Modelo do carro
        ano:
          type: integer
          description: Ano do carro
        placa:
          type: string
          description: Placa do carro
          example: 'ABC1234'
      required:
        - marca
        - modelo
        - ano
        - placa
responses:
  200:
    description: Carro atualizado com sucesso
    schema:
      type: object
      properties:
        carro:
          type: object
          properties:
            id:
              type: integer
              description: ID do carro
            marca:
              type: string
              description: Marca do carro
            modelo:
              type: string
              description: Modelo do carro
            ano:
              type: integer
              description: Ano do carro
            placa:
              type: string
              description: Placa do carro
              example: 'ABC1234'
        message:
          type: string
          description: Mensagem de sucesso
  404:
    description: Carro não encontrado
    schema:
      type: object
      properties:
        erro:
          type: string
          description: Mensagem de erro
